// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package com.poc.grpc.user;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
